name = "soulmate"                  # 必须和小写项目名一致
compatibility_date = "2026-02-23"  # 当前或未来日期

# 纯静态资产配置（Vite 构建输出）
[assets]
directory = "./dist"               # 指向 dist 目录

# 支持 SPA 单页应用路由（重要！防止刷新 404）
not_found_handling = "single-page-application"